@startuml
title Hierarquia de java.util.ArrayList - Java 21

interface Iterable<E>
interface Collection<E>
interface List<E>

class ArrayList<E>

Iterable <|-- Collection
Collection <|-- List
List <|.. ArrayList

@enduml
