@startuml
skinparam classAttributeIconSize 0

interface Iterable<E>
interface Collection<E>
interface SequencedCollection<E>

interface List<E>
interface Set<E>
interface SequencedSet<E>
interface SortedSet<E>
interface NavigableSet<E>

interface Queue<E>
interface Deque<E>

interface Map<K, V>
interface SequencedMap<K, V>
interface SortedMap<K, V>
interface NavigableMap<K, V>

Iterable <|-- Collection

Collection <|-- SequencedCollection
SequencedCollection <|-- List

Collection <|-- Set
Set <|-- SequencedSet
SequencedCollection <|-- SequencedSet
SequencedSet <|-- SortedSet
SortedSet <|-right- NavigableSet

Collection <|-- Queue
Queue <|-- Deque
SequencedCollection <|-- Deque

Map <|-- SequencedMap
SequencedMap <|-- SortedMap
SortedMap <|-- NavigableMap

@enduml
