@startuml
title Hierarquia de java.util.TreeSet - Java 21

interface Iterable<E>
interface Collection<E>
interface Set<E>

class TreeSet<E>

Iterable <|-- Collection
Collection <|-- Set
Set <|.. TreeSet

@enduml
