@startuml
title java.io - OutputStream

skinparam classAttributeIconSize 0
skinparam linetype ortho

interface Closeable
interface Flushable

abstract class OutputStream {
  +write(int): void
  +write(byte[]): void
  +flush(): void
  +close(): void
}

class FileOutputStream
class FilterOutputStream
class BufferedOutputStream
class DataOutputStream
class ObjectOutputStream

Closeable <|.. OutputStream
Flushable <|.. OutputStream

OutputStream <|-- FileOutputStream
OutputStream <|-- FilterOutputStream
OutputStream <|-- ObjectOutputStream

FilterOutputStream <|-- BufferedOutputStream
FilterOutputStream <|-- DataOutputStream

@enduml
