@startuml
title java.nio.file - classes principais

skinparam classAttributeIconSize 0
skinparam linetype ortho
set separator none

interface Path
class Files
class Paths
class FileSystems
interface FileSystem
interface DirectoryStream<T>
enum StandardOpenOption
enum StandardCopyOption
enum LinkOption

Paths ..> Path
Files ..> Path
FileSystems ..> FileSystem
FileSystem ..> Path
Files ..> DirectoryStream
Path ..> FileSystem

@enduml
