@startuml
title java.io - Reader

skinparam classAttributeIconSize 0
skinparam linetype ortho

interface Readable
interface Closeable

abstract class Reader {
  +read(): int
  +read(char[]): int
  +skip(long): long
  +close(): void
}

class BufferedReader
class InputStreamReader
class FileReader

Readable <|.. Reader
Closeable <|.. Reader

Reader <|-- BufferedReader
Reader <|-- InputStreamReader

InputStreamReader <|.right. FileReader

BufferedReader ..> Reader

@enduml
