@startuml
title java.io - Writer

skinparam classAttributeIconSize 0
skinparam linetype ortho

interface Appendable
interface Closeable
interface Flushable

abstract class Writer {
  +write(String): void
  +append(CharSequence): Writer
  +flush(): void
  +close(): void
}

class BufferedWriter
class OutputStreamWriter
class FileWriter

Appendable <|.. Writer
Closeable <|.. Writer
Flushable <|.. Writer

Writer <|-- BufferedWriter
Writer <|-- OutputStreamWriter

OutputStreamWriter <|.right. FileWriter

BufferedWriter ..> Writer
@enduml
