@startuml
title java.io - InputStream

skinparam classAttributeIconSize 0
skinparam linetype ortho

interface Closeable

abstract class InputStream {
  +read(): int
  +read(byte[]): int
  +skip(long): long
  +close(): void
}

class FileInputStream
class FilterInputStream
class BufferedInputStream
class DataInputStream
class ObjectInputStream

Closeable <|.. InputStream

InputStream <|-- FileInputStream
InputStream <|-- FilterInputStream
InputStream <|-- ObjectInputStream

FilterInputStream <|-- BufferedInputStream
FilterInputStream <|-- DataInputStream

@enduml
